In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [2]:
housing_original = pd.read_csv("housing.csv")
housing_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [3]:
housing_original.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
housing_original.iloc[:, 5:].head()

   population  households  median_income  median_house_value ocean_proximity
0       322.0       126.0         8.3252            452600.0        NEAR BAY
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY
2       496.0       177.0         7.2574            352100.0        NEAR BAY
3       558.0       219.0         5.6431            341300.0        NEAR BAY
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
housing_original['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [6]:
housing = housing_original[housing_original['ocean_proximity'] !='ISLAND'] 
housing['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
Name: count, dtype: int64

In [7]:
housing = pd.get_dummies(housing, columns = ['ocean_proximity'], dtype = int, prefix = 'dmy')

In [8]:
housing.iloc[[1, 200, 1000, 1850, 5000], 9:]

      dmy_<1H OCEAN  dmy_INLAND  dmy_NEAR BAY  dmy_NEAR OCEAN
1                 0           0             1               0
200               0           0             1               0
1000              0           1             0               0
1850              0           0             0               1
5000              1           0             0               0

In [9]:
train_full, test = train_test_split(housing, test_size=0.2, random_state=40) 
train, val = train_test_split(train_full, test_size=0.25, random_state=36)

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12381 entries, 12054 to 14298
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           12381 non-null  float64
 1   latitude            12381 non-null  float64
 2   housing_median_age  12381 non-null  float64
 3   total_rooms         12381 non-null  float64
 4   total_bedrooms      12261 non-null  float64
 5   population          12381 non-null  float64
 6   households          12381 non-null  float64
 7   median_income       12381 non-null  float64
 8   median_house_value  12381 non-null  float64
 9   dmy_<1H OCEAN       12381 non-null  int64
 10  dmy_INLAND          12381 non-null  int64
 11  dmy_NEAR BAY        12381 non-null  int64
 12  dmy_NEAR OCEAN      12381 non-null  int64
dtypes: float64(9), int64(4)
memory usage: 1.3 MB

In [11]:
train = train.dropna()
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12261 entries, 12054 to 14298
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           12261 non-null  float64
 1   latitude            12261 non-null  float64
 2   housing_median_age  12261 non-null  float64
 3   total_rooms         12261 non-null  float64
 4   total_bedrooms      12261 non-null  float64
 5   population          12261 non-null  float64
 6   households          12261 non-null  float64
 7   median_income       12261 non-null  float64
 8   median_house_value  12261 non-null  float64
 9   dmy_<1H OCEAN       12261 non-null  int64
 10  dmy_INLAND          12261 non-null  int64
 11  dmy_NEAR BAY        12261 non-null  int64
 12  dmy_NEAR OCEAN      12261 non-null  int64
dtypes: float64(9), int64(4)
memory usage: 1.3 MB

In [12]:
val = val.dropna()
test = test.dropna()

In [13]:
X_train_full = train_full.drop(columns=['median_house_value']) 
y_train_full = train_full['median_house_value']
X_train, y_train = train.drop(columns=['median_house_value']), train['median_house_value']
X_val, y_val = val.drop(columns=['median_house_value']), val['median_house_value']
X_test, y_test = test.drop(columns=['median_house_value']),test['median_house_value']

In [14]:
linreg = LinearRegression()

In [15]:
params_list = [{"n_estimators": 100, "max_depth": 20}, {"n_estimators": 200, "max_depth": 30}, {"n_estimators": 600, "max_depth": None}, {"n_estimators": 300, "max_depth": 20, "min_samples_split": 5}, {"n_estimators": 400, "max_depth": None, "min_samples_leaf": 2}]
 
best_rmse = float("inf")
best_params = None
best_model = None

In [16]:
for params in params_list:
    rf = RandomForestRegressor(random_state=42, n_jobs=-1, **params)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_val)
    rmse = root_mean_squared_error(y_val, y_pred)

    print(f"Hyperparameters: {params} -> RMSE: {rmse:.2f}")

Hyperparameters: {'n_estimators': 100, 'max_depth': 20} -> RMSE: 49664.13
Hyperparameters: {'n_estimators': 200, 'max_depth': 30} -> RMSE: 49554.89
Hyperparameters: {'n_estimators': 600, 'max_depth': None} -> RMSE: 49489.90
Hyperparameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 5} -> RMSE: 49604.16
Hyperparameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_leaf': 2} -> RMSE: 49330.61